services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8000}:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:${DB_PASSWORD:-postgres}@db:5432/horilla"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
    name: ${VOLUME_NAME:-horilla_postgresql_data} 